### ISSUE TITLE
Deploy agents to a separate namespace

### ISSUE THREAD

**Issue by chelnak** [SkillsFundingAgency/das-azure-pipelines-agents#19]
Use a separate namespace for agents such as `azure-pipelines-agents`. Keep `default` for management tooling.

**Comment by mwevill** [comment]
From checking it looks like we would need to create an kubectl apply taks with a YAML similar to this.

kind: Namespace
apiVersion: v1
metadata:
  
  name: test
  
  labels:
    
    name: test
kubectl
apply -f test.yaml
Then update pipeline release tasks to deploy to namespace.
