### ISSUE TITLE
Issue with Required Module ester, PSScriptAnalyzer

### ISSUE THREAD

**Issue by mwevill** [SkillsFundingAgency/das-azure-pipelines-agents#40]
Running a Pipeline that has a script that uses Pester, PSScriptAnalyzer.  Fails due to module not being installed. Subsequent runs succeed.

**Comment by jack-education** [comment]
Closing this and https://github.com/SkillsFundingAgency/das-azure-pipelines-agents/pull/41 as issue confirmed as resolved by requiring PowerShell Core for PowerShell task.
