### ISSUE TITLE
Memory pressure likely causing the expired pods / offline agents

### ISSUE THREAD

**Issue by mwevill** [SkillsFundingAgency/das-azure-pipelines-agents#44]

**Comment by nbowes24** [comment]
After cleaning up the expired pods we have not had anymore in the last 7 days. We will continue to monitor this situation. A possible cause was the stress from intensive sonarcloud analysis before the rules were toned down.

**Comment by nbowes24** [comment]
VM Size was not sufficient for the builds due to almost half of the memory being reserved.

New VM Size can now handle multiple sonar scans without getting close to memory limits. Will be monitoring to see if memory limits are required in the future.
